spring:
  application:
    name: users
  config:
    import: optional:configserver:http://localhost:8888
  mail:
    host: smtp.gmail.com
    port: 587
    username: llpmanagement.123@gmail.com
    password: qhbdwwcdlssoxqpu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true