eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  address: 0.0.0.0
  port: 8089
spring:
  application:
    name: commons
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://LAPTOP-FEV4I7LE;databaseName=LLPCommon;encrypt=true;trustServerCertificate=true
    username: sa
    password: long70261209
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database: sql_server
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
#spring:
#  application:
#    name: commons
#  datasource:
#    url: jdbc:mysql://localhost:3306/llpcommon
#    username: root
#    password: long70261209
#  jpa:
#    hibernate:
#      ddl-auto: none
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#      database: mysql
#      database-platform: org.hibernate.dialect.MySQL8Dialect