eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: commons
          uri: http://localhost:8089
          predicates:
            - Path=/api/common/**
          filters:
            - AuthenticationFilter
        - id: courses
          uri: http://localhost:8090
          predicates:
            - Path=/api/course/**
          filters:
            - AuthenticationFilter
        - id: orders
          uri: http://localhost:8091
          predicates:
            - Path=/api/order/**
          filters:
            - AuthenticationFilter
        - id: users
          uri: http://localhost:8092
          predicates:
            - Path=/api/user/**