eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  address: 0.0.0.0
  port: 8092
spring:
  application:
    name: users
  datasource:
    url: jdbc:mysql://localhost:3306/llpuser
    username: root
    password: long70261209
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      database: mysql
      database-platform: org.hibernate.dialect.MySQL8Dialect
#spring:
#  application:
#    name: users
#  datasource:
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#    url: jdbc:sqlserver://LAPTOP-FEV4I7LE;databaseName=LLPUser;encrypt=true;trustServerCertificate=true
#    username: sa
#    password: long70261209
#  jpa:
#    hibernate:
#      ddl-auto: none
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#    database: sql_server
#    database-platform: org.hibernate.dialect.SQLServer2012Dialect
